export const codeTemplates: Record<string, string> = {
  java: [
    "import java.util.*;",
    "",
    "public class Main {",
    "    public static void main(String[] args) {",
    "        // 读取输入",
    "        Scanner sc = new Scanner(System.in);",
    "",
    "        // 在此编写解题逻辑",
    "",
    "    }",
    "}",
  ].join("\n"),

  cpp: [
    "#include <bits/stdc++.h>",
    "using namespace std;",
    "",
    "int main() {",
    "    ios::sync_with_stdio(false);",
    "    cin.tie(nullptr);",
    "",
    "    // 在此编写解题逻辑",
    "",
    "    return 0;",
    "}",
  ].join("\n"),

  go: [
    "package main",
    "",
    "import (",
    '    "bufio"',
    '    "fmt"',
    '    "os"',
    ")",
    "",
    "func main() {",
    "    reader := bufio.NewReader(os.Stdin)",
    "    _ = reader",
    "",
    "    // 在此编写解题逻辑",
    "    fmt.Println()",
    "}",
  ].join("\n"),

  html: [
    "<!DOCTYPE html>",
    '<html lang="zh">',
    "<head>",
    '    <meta charset="UTF-8">',
    "    <title>Solution</title>",
    "</head>",
    "<body>",
    "    <!-- 在此编写内容 -->",
    "    <script>",
    "        // JavaScript 逻辑",
    "    <" + "/script>",
    "</body>",
    "</html>",
  ].join("\n"),
};
